- name: fn
  label: Full name
  required: true
- name: email
  type: email
  label: E-mail
  required: true
- name: tel
  type: tel
  label: Telephone
- name: url
  type: url
  label: Web-site
- name: photo
  type: url
  label: Photo
- name: title
  label: Title
  required: true
- name: org
  label: Organization
